CBU_SAMPLE1=Sample1
CBU_SAMPLE2=Sample2
CBU_SAMPLE3=Sample3

all:
	$(MAKE) -C $(CBU_SAMPLE1)
	$(MAKE) -C $(CBU_SAMPLE2)
	$(MAKE) -C $(CBU_SAMPLE3)

clean:
	$(MAKE) -C $(CBU_SAMPLE1) clean
	$(MAKE) -C $(CBU_SAMPLE2) clean
	$(MAKE) -C $(CBU_SAMPLE3) clean
